# Generated by Django 5.0.6 on 2025-04-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='wrong_answers',
            field=models.TextField(default='[]', help_text='JSON-encoded list of wrong answers'),
        ),
    ]
