# Generated by Django 5.0.6 on 2025-04-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_question_wrong_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='wrong_answers',
            field=models.TextField(help_text='JSON list of wrong answers'),
        ),
    ]
